"""rewards marketplace

Revision ID: 075e3c13a8eb
Revises: 7d81fd336deb
Create Date: 2026-07-02 00:32:57.942129

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements


# revision identifiers, used by Alembic.
revision: str = "075e3c13a8eb"
down_revision: str | None = "7d81fd336deb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reward_items",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("points_cost", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reward_items")),
    )
    op.create_index(op.f("ix_reward_items_tenant_id"), "reward_items", ["tenant_id"], unique=False)
    op.create_table(
        "reward_redemptions",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("reward_item_id", sa.UUID(), nullable=False),
        sa.Column("points_spent", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="completed", nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reward_item_id"],
            ["reward_items.id"],
            name=op.f("fk_reward_redemptions_reward_item_id_reward_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reward_redemptions")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_reward_redemptions_idem"),
    )
    op.create_index(
        op.f("ix_reward_redemptions_player_id"), "reward_redemptions", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_reward_redemptions_reward_item_id"),
        "reward_redemptions",
        ["reward_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reward_redemptions_tenant_id"), "reward_redemptions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in ("reward_items", "reward_redemptions"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("reward_items", "reward_redemptions"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reward_redemptions_tenant_id"), table_name="reward_redemptions")
    op.drop_index(op.f("ix_reward_redemptions_reward_item_id"), table_name="reward_redemptions")
    op.drop_index(op.f("ix_reward_redemptions_player_id"), table_name="reward_redemptions")
    op.drop_table("reward_redemptions")
    op.drop_index(op.f("ix_reward_items_tenant_id"), table_name="reward_items")
    op.drop_table("reward_items")
    # ### end Alembic commands ###
