"""content items

Revision ID: 24c7cfb725a4
Revises: c90137cab6fa
Create Date: 2026-07-01 23:28:36.957168

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "24c7cfb725a4"
down_revision: str | None = "c90137cab6fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_items",
        sa.Column("content_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("media_url", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("segment", sa.String(length=100), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_index(
        op.f("ix_content_items_tenant_id"), "content_items", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for stmt in enable_rls_statements("content_items"):
        op.execute(stmt)


def downgrade() -> None:
    for stmt in disable_rls_statements("content_items"):
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_items_tenant_id"), table_name="content_items")
    op.drop_table("content_items")
    # ### end Alembic commands ###
