"""reservations + valet

Revision ID: 298f119efdef
Revises: 3826f5990172
Create Date: 2026-07-01 23:58:36.282613

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "298f119efdef"
down_revision: str | None = "3826f5990172"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="requested", nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(op.f("ix_reservations_player_id"), "reservations", ["player_id"], unique=False)
    op.create_index(op.f("ix_reservations_tenant_id"), "reservations", ["tenant_id"], unique=False)
    op.create_table(
        "valet_requests",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("ticket_ref", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="requested", nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_valet_requests")),
    )
    op.create_index(
        op.f("ix_valet_requests_player_id"), "valet_requests", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_valet_requests_tenant_id"), "valet_requests", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in ("reservations", "valet_requests"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("reservations", "valet_requests"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_valet_requests_tenant_id"), table_name="valet_requests")
    op.drop_index(op.f("ix_valet_requests_player_id"), table_name="valet_requests")
    op.drop_table("valet_requests")
    op.drop_index(op.f("ix_reservations_tenant_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_player_id"), table_name="reservations")
    op.drop_table("reservations")
    # ### end Alembic commands ###
