"""wallets + wallet_transactions ledger

Revision ID: 3826f5990172
Revises: 50613014b5e1
Create Date: 2026-07-01 23:53:21.363012

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "3826f5990172"
down_revision: str | None = "50613014b5e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("balance_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
        sa.UniqueConstraint("tenant_id", "player_id", name="uq_wallets_tenant_id_player_id"),
    )
    op.create_index(op.f("ix_wallets_player_id"), "wallets", ["player_id"], unique=False)
    op.create_index(op.f("ix_wallets_tenant_id"), "wallets", ["tenant_id"], unique=False)
    op.create_table(
        "wallet_transactions",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("egm_id", sa.String(length=100), nullable=True),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="completed", nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
            name=op.f("fk_wallet_transactions_wallet_id_wallets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_transactions")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_wallet_txn_tenant_id_idem"),
    )
    op.create_index(
        op.f("ix_wallet_transactions_player_id"), "wallet_transactions", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_transactions_tenant_id"), "wallet_transactions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_transactions_wallet_id"), "wallet_transactions", ["wallet_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in ("wallets", "wallet_transactions"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)

    # Enforce ledger immutability at the database: block UPDATE/DELETE on wallet_transactions.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_wallet_txn_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'wallet_transactions is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER wallet_txn_immutable "
        "BEFORE UPDATE OR DELETE ON wallet_transactions "
        "FOR EACH ROW EXECUTE FUNCTION prevent_wallet_txn_mutation();"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS wallet_txn_immutable ON wallet_transactions;")
    op.execute("DROP FUNCTION IF EXISTS prevent_wallet_txn_mutation();")
    for table in ("wallets", "wallet_transactions"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_transactions_wallet_id"), table_name="wallet_transactions")
    op.drop_index(op.f("ix_wallet_transactions_tenant_id"), table_name="wallet_transactions")
    op.drop_index(op.f("ix_wallet_transactions_player_id"), table_name="wallet_transactions")
    op.drop_table("wallet_transactions")
    op.drop_index(op.f("ix_wallets_tenant_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_player_id"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
