"""tenant config appearance

Revision ID: 39a1c2a88bf0
Revises: 9f4ad8eadf22
Create Date: 2026-07-02 21:41:17.403122

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a1c2a88bf0'
down_revision: str | None = '9f4ad8eadf22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_configs', sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_configs', 'appearance')
    # ### end Alembic commands ###
