"""digital keys

Revision ID: 44dc6a6673af
Revises: 298f119efdef
Create Date: 2026-07-02 00:02:36.485490

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements


# revision identifiers, used by Alembic.
revision: str = "44dc6a6673af"
down_revision: str | None = "298f119efdef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digital_keys",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("room", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=30), server_default="mock", nullable=False),
        sa.Column("mobile_key_ref", sa.String(length=200), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_digital_keys_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digital_keys")),
    )
    op.create_index(op.f("ix_digital_keys_player_id"), "digital_keys", ["player_id"], unique=False)
    op.create_index(
        op.f("ix_digital_keys_reservation_id"), "digital_keys", ["reservation_id"], unique=False
    )
    op.create_index(op.f("ix_digital_keys_tenant_id"), "digital_keys", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    for stmt in enable_rls_statements("digital_keys"):
        op.execute(stmt)


def downgrade() -> None:
    for stmt in disable_rls_statements("digital_keys"):
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_digital_keys_tenant_id"), table_name="digital_keys")
    op.drop_index(op.f("ix_digital_keys_reservation_id"), table_name="digital_keys")
    op.drop_index(op.f("ix_digital_keys_player_id"), table_name="digital_keys")
    op.drop_table("digital_keys")
    # ### end Alembic commands ###
