"""notifications + deliveries

Revision ID: 4f2583a7d988
Revises: 44dc6a6673af
Create Date: 2026-07-02 00:07:00.846980

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f2583a7d988"
down_revision: str | None = "44dc6a6673af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("segment", sa.String(length=100), nullable=True),
        sa.Column("deep_link", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schedule_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("receipt_ref", sa.String(length=200), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_deliveries_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    op.create_index(
        op.f("ix_notification_deliveries_notification_id"),
        "notification_deliveries",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_player_id"),
        "notification_deliveries",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_tenant_id"),
        "notification_deliveries",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    for table in ("notifications", "notification_deliveries"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("notifications", "notification_deliveries"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_deliveries_tenant_id"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_player_id"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_notification_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
