"""player kyc_status + devices

Revision ID: 50613014b5e1
Revises: ce8d20d33c35
Create Date: 2026-07-01 23:44:32.338144

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "50613014b5e1"
down_revision: str | None = "ce8d20d33c35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("push_token", sa.String(length=500), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("tenant_id", "push_token", name="uq_devices_tenant_id_push_token"),
    )
    op.create_index(op.f("ix_devices_player_id"), "devices", ["player_id"], unique=False)
    op.create_index(op.f("ix_devices_tenant_id"), "devices", ["tenant_id"], unique=False)
    op.add_column(
        "players",
        sa.Column("kyc_status", sa.String(length=20), server_default="unstarted", nullable=False),
    )
    # ### end Alembic commands ###

    for stmt in enable_rls_statements("devices"):
        op.execute(stmt)


def downgrade() -> None:
    for stmt in disable_rls_statements("devices"):
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "kyc_status")
    op.drop_index(op.f("ix_devices_tenant_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_player_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
