"""geofencing zones, beacons, triggers, events + consent

Revision ID: 65386d404a8e
Revises: 4f2583a7d988
Create Date: 2026-07-02 00:15:13.277295

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65386d404a8e"
down_revision: str | None = "4f2583a7d988"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geofence_zones",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=10), server_default="gps", nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=True),
        sa.Column("center_lng", sa.Float(), nullable=True),
        sa.Column("radius_m", sa.Integer(), nullable=True),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geofence_zones")),
    )
    op.create_index(
        op.f("ix_geofence_zones_tenant_id"), "geofence_zones", ["tenant_id"], unique=False
    )
    op.create_table(
        "location_events",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("trigger_id", sa.UUID(), nullable=True),
        sa.Column("event", sa.String(length=10), nullable=False),
        sa.Column("dwell_seconds", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_events")),
    )
    op.create_index(
        op.f("ix_location_events_player_id"), "location_events", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_location_events_tenant_id"), "location_events", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_location_events_zone_id"), "location_events", ["zone_id"], unique=False
    )
    op.create_table(
        "beacons",
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=False),
        sa.Column("major", sa.Integer(), nullable=False),
        sa.Column("minor", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["geofence_zones.id"],
            name=op.f("fk_beacons_zone_id_geofence_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beacons")),
    )
    op.create_index(op.f("ix_beacons_tenant_id"), "beacons", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_beacons_zone_id"), "beacons", ["zone_id"], unique=False)
    op.create_table(
        "location_triggers",
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("event", sa.String(length=10), nullable=False),
        sa.Column("dwell_seconds", sa.Integer(), nullable=True),
        sa.Column("offer_id", sa.UUID(), nullable=True),
        sa.Column("segment", sa.String(length=100), nullable=True),
        sa.Column("frequency_cap_per_day", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["geofence_zones.id"],
            name=op.f("fk_location_triggers_zone_id_geofence_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_triggers")),
    )
    op.create_index(
        op.f("ix_location_triggers_tenant_id"), "location_triggers", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_location_triggers_zone_id"), "location_triggers", ["zone_id"], unique=False
    )
    op.add_column(
        "players",
        sa.Column("location_consent", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###

    for table in ("geofence_zones", "beacons", "location_triggers", "location_events"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("geofence_zones", "beacons", "location_triggers", "location_events"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "location_consent")
    op.drop_index(op.f("ix_location_triggers_zone_id"), table_name="location_triggers")
    op.drop_index(op.f("ix_location_triggers_tenant_id"), table_name="location_triggers")
    op.drop_table("location_triggers")
    op.drop_index(op.f("ix_beacons_zone_id"), table_name="beacons")
    op.drop_index(op.f("ix_beacons_tenant_id"), table_name="beacons")
    op.drop_table("beacons")
    op.drop_index(op.f("ix_location_events_zone_id"), table_name="location_events")
    op.drop_index(op.f("ix_location_events_tenant_id"), table_name="location_events")
    op.drop_index(op.f("ix_location_events_player_id"), table_name="location_events")
    op.drop_table("location_events")
    op.drop_index(op.f("ix_geofence_zones_tenant_id"), table_name="geofence_zones")
    op.drop_table("geofence_zones")
    # ### end Alembic commands ###
