"""games catalog + favorites

Revision ID: 7d81fd336deb
Revises: d08173bc528d
Create Date: 2026-07-02 00:28:03.552480

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements


# revision identifiers, used by Alembic.
revision: str = "7d81fd336deb"
down_revision: str | None = "d08173bc528d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=True),
        sa.Column("volatility", sa.String(length=20), nullable=True),
        sa.Column("is_jackpot", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("jackpot_amount_cents", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    op.create_index(op.f("ix_games_category"), "games", ["category"], unique=False)
    op.create_index(op.f("ix_games_tenant_id"), "games", ["tenant_id"], unique=False)
    op.create_table(
        "player_favorites",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_favorites_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_favorites")),
        sa.UniqueConstraint("tenant_id", "player_id", "game_id", name="uq_player_favorites_unique"),
    )
    op.create_index(
        op.f("ix_player_favorites_game_id"), "player_favorites", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_favorites_player_id"), "player_favorites", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_favorites_tenant_id"), "player_favorites", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in ("games", "player_favorites"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("games", "player_favorites"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_favorites_tenant_id"), table_name="player_favorites")
    op.drop_index(op.f("ix_player_favorites_player_id"), table_name="player_favorites")
    op.drop_index(op.f("ix_player_favorites_game_id"), table_name="player_favorites")
    op.drop_table("player_favorites")
    op.drop_index(op.f("ix_games_tenant_id"), table_name="games")
    op.drop_index(op.f("ix_games_category"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
