"""tenants table

Revision ID: 96f364261601
Revises: 38c9b6141be2
Create Date: 2026-07-01 20:27:25.180842

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import APP_RLS_ROLE, create_app_role_statements

# revision identifiers, used by Alembic.
revision: str = "96f364261601"
down_revision: str | None = "38c9b6141be2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The non-privileged runtime role the request path switches into so RLS is enforced.
    for stmt in create_app_role_statements():
        op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    # ### end Alembic commands ###

    # tenants is not tenant-owned (no RLS); the RLS role only needs to read the registry.
    op.execute(f"GRANT SELECT ON tenants TO {APP_RLS_ROLE};")


def downgrade() -> None:
    op.execute(f"REVOKE SELECT ON tenants FROM {APP_RLS_ROLE};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
