"""concierge answers + rg flags

Revision ID: 9f4ad8eadf22
Revises: a1db0b911e7d
Create Date: 2026-07-02 20:50:46.846306

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = '9f4ad8eadf22'
down_revision: str | None = 'a1db0b911e7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concierge_answers',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('use_case', sa.String(length=20), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concierge_answers'))
    )
    op.create_index(op.f('ix_concierge_answers_player_id'), 'concierge_answers', ['player_id'], unique=False)
    op.create_index(op.f('ix_concierge_answers_tenant_id'), 'concierge_answers', ['tenant_id'], unique=False)
    op.add_column('players', sa.Column('rg_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    # Tenant isolation (GOLDEN RULE #1).
    for stmt in enable_rls_statements("concierge_answers"):
        op.execute(stmt)

    # concierge_answers is append-only (GOLDEN RULE #8) — same trigger pattern as audit_logs.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_concierge_answer_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'concierge_answers is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER concierge_answers_immutable BEFORE UPDATE OR DELETE ON concierge_answers "
        "FOR EACH ROW EXECUTE FUNCTION prevent_concierge_answer_mutation();"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS concierge_answers_immutable ON concierge_answers;")
    op.execute("DROP FUNCTION IF EXISTS prevent_concierge_answer_mutation();")
    for stmt in disable_rls_statements("concierge_answers"):
        op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rg_flags')
    op.drop_index(op.f('ix_concierge_answers_tenant_id'), table_name='concierge_answers')
    op.drop_index(op.f('ix_concierge_answers_player_id'), table_name='concierge_answers')
    op.drop_table('concierge_answers')
    # ### end Alembic commands ###
