"""concierge data model

Revision ID: a1c282422293
Revises: b4e1f77d98c0
Create Date: 2026-07-02 20:32:05.609751

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = 'a1c282422293'
down_revision: str | None = 'b4e1f77d98c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_properties_tenant_id_name')
    )
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_table('player_preferences',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('favorite_property_id', sa.UUID(), nullable=True),
    sa.Column('favorite_dining', sa.String(length=120), nullable=True),
    sa.Column('favorite_experiences', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_property_id'], ['properties.id'], name=op.f('fk_player_preferences_favorite_property_id_properties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_preferences_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_preferences')),
    sa.UniqueConstraint('tenant_id', 'player_id', name='uq_player_preferences_tenant_id_player')
    )
    op.create_index(op.f('ix_player_preferences_tenant_id'), 'player_preferences', ['tenant_id'], unique=False)
    op.add_column('players', sa.Column('home_origin', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('players', sa.Column('concierge_consent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Tenant isolation (GOLDEN RULE #1): enable + FORCE RLS on the new tenant-owned tables.
    for table in ("properties", "player_preferences"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("player_preferences", "properties"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'concierge_consent')
    op.drop_column('players', 'home_origin')
    op.drop_index(op.f('ix_player_preferences_tenant_id'), table_name='player_preferences')
    op.drop_table('player_preferences')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
