"""tenant config concierge settings

Revision ID: a1db0b911e7d
Revises: a1c282422293
Create Date: 2026-07-02 20:40:30.203596

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1db0b911e7d'
down_revision: str | None = 'a1c282422293'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_configs', sa.Column('concierge', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_configs', 'concierge')
    # ### end Alembic commands ###
