"""tenant config and themes

Revision ID: c90137cab6fa
Revises: e11a759e902c
Create Date: 2026-07-01 22:46:08.800382

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "c90137cab6fa"
down_revision: str | None = "e11a759e902c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_configs",
        sa.Column("api_base_url", sa.String(length=500), nullable=True),
        sa.Column(
            "feature_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "endpoints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "navigation",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_configs")),
        sa.UniqueConstraint("tenant_id", name="uq_tenant_configs_tenant_id"),
    )
    op.create_index(
        op.f("ix_tenant_configs_tenant_id"), "tenant_configs", ["tenant_id"], unique=False
    )
    op.create_table(
        "themes",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "tokens",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("logo_ref", sa.String(length=500), nullable=True),
        sa.Column("splash_ref", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
    )
    op.create_index(op.f("ix_themes_tenant_id"), "themes", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # Tenant-isolation RLS on the tenant-owned config/theme tables (GOLDEN RULE #1).
    for table in ("tenant_configs", "themes"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("tenant_configs", "themes"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_themes_tenant_id"), table_name="themes")
    op.drop_table("themes")
    op.drop_index(op.f("ix_tenant_configs_tenant_id"), table_name="tenant_configs")
    op.drop_table("tenant_configs")
    # ### end Alembic commands ###
