"""offers, promotions, redemptions, player segment

Revision ID: ce8d20d33c35
Revises: 24c7cfb725a4
Create Date: 2026-07-01 23:39:17.952548

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_rls_statements, enable_rls_statements

# revision identifiers, used by Alembic.
revision: str = "ce8d20d33c35"
down_revision: str | None = "24c7cfb725a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("segment", sa.String(length=100), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    op.create_index(op.f("ix_offers_kind"), "offers", ["kind"], unique=False)
    op.create_index(op.f("ix_offers_tenant_id"), "offers", ["tenant_id"], unique=False)
    op.create_table(
        "player_offers",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="redeemed", nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
            name=op.f("fk_player_offers_offer_id_offers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_offers")),
        sa.UniqueConstraint("tenant_id", "player_id", "offer_id", name="uq_player_offers_unique"),
    )
    op.create_index(op.f("ix_player_offers_offer_id"), "player_offers", ["offer_id"], unique=False)
    op.create_index(
        op.f("ix_player_offers_player_id"), "player_offers", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_offers_tenant_id"), "player_offers", ["tenant_id"], unique=False
    )
    op.add_column("players", sa.Column("segment", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    for table in ("offers", "player_offers"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)


def downgrade() -> None:
    for table in ("offers", "player_offers"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "segment")
    op.drop_index(op.f("ix_player_offers_tenant_id"), table_name="player_offers")
    op.drop_index(op.f("ix_player_offers_player_id"), table_name="player_offers")
    op.drop_index(op.f("ix_player_offers_offer_id"), table_name="player_offers")
    op.drop_table("player_offers")
    op.drop_index(op.f("ix_offers_tenant_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_kind"), table_name="offers")
    op.drop_table("offers")
    # ### end Alembic commands ###
