"""identity, rbac, players

Revision ID: e11a759e902c
Revises: 96f364261601
Create Date: 2026-07-01 20:47:16.634040

"""

from __future__ import annotations

from collections.abc import Sequence

import uuid

from alembic import op
import sqlalchemy as sa

from app.db.rls import enable_rls_statements, disable_rls_statements
from app.rbac.matrix import ROLE_LABELS, ROLE_PERMISSIONS, all_permissions, split_permission

# revision identifiers, used by Alembic.
revision: str = "e11a759e902c"
down_revision: str | None = "96f364261601"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_index(op.f("ix_permissions_key"), "permissions", ["key"], unique=True)
    op.create_table(
        "player_otps",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_otps")),
    )
    op.create_index(op.f("ix_player_otps_email"), "player_otps", ["email"], unique=False)
    op.create_index(op.f("ix_player_otps_tenant_id"), "player_otps", ["tenant_id"], unique=False)
    op.create_table(
        "players",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_players_tenant_id_email"),
    )
    op.create_index(op.f("ix_players_email"), "players", ["email"], unique=False)
    op.create_index(op.f("ix_players_tenant_id"), "players", ["tenant_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("audience", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(
        op.f("ix_refresh_tokens_subject_id"), "refresh_tokens", ["subject_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_key"), "roles", ["key"], unique=True)
    op.create_table(
        "admin_user_tenants",
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_user_tenants_admin_user_id_admin_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_admin_user_tenants_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("admin_user_id", "tenant_id", name=op.f("pk_admin_user_tenants")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_user_roles_admin_user_id_admin_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("admin_user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # ### end Alembic commands ###

    # Enable tenant-isolation RLS on the tenant-owned tables (GOLDEN RULE #1).
    for table in ("players", "player_otps"):
        for stmt in enable_rls_statements(table):
            op.execute(stmt)

    # Player auth runs under the app_rls role (for RLS) but also records refresh tokens
    # (a global, non-tenant table), so grant it the needed DML there.
    op.execute("GRANT SELECT, INSERT, UPDATE ON refresh_tokens TO app_rls;")

    _seed_rbac()


def _seed_rbac() -> None:
    """Seed roles, permissions and role_permissions exactly from Appendix C."""
    bind = op.get_bind()

    permission_ids: dict[str, uuid.UUID] = {}
    for perm in all_permissions():
        resource, action = split_permission(perm)
        pid = uuid.uuid4()
        permission_ids[perm.value] = pid
        bind.execute(
            sa.text(
                "INSERT INTO permissions (id, key, resource, action) "
                "VALUES (:id, :key, :resource, :action)"
            ),
            {"id": pid, "key": perm.value, "resource": resource, "action": action},
        )

    for role, permissions in ROLE_PERMISSIONS.items():
        rid = uuid.uuid4()
        bind.execute(
            sa.text("INSERT INTO roles (id, key, name, is_system) VALUES (:id, :key, :name, true)"),
            {"id": rid, "key": role.value, "name": ROLE_LABELS[role]},
        )
        for perm in permissions:
            bind.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_id) "
                    "VALUES (:role_id, :permission_id)"
                ),
                {"role_id": rid, "permission_id": permission_ids[perm.value]},
            )


def downgrade() -> None:
    for table in ("player_otps", "players"):
        for stmt in disable_rls_statements(table):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("admin_user_tenants")
    op.drop_index(op.f("ix_roles_key"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_refresh_tokens_subject_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_players_tenant_id"), table_name="players")
    op.drop_index(op.f("ix_players_email"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_player_otps_tenant_id"), table_name="player_otps")
    op.drop_index(op.f("ix_player_otps_email"), table_name="player_otps")
    op.drop_table("player_otps")
    op.drop_index(op.f("ix_permissions_key"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
