#!/usr/bin/env node
/**
 * Design-token codegen (audit M9). `design/tokens.json` is the single source of truth for the
 * white-label default palette + type/space scales. This script mirrors it into:
 *   - apps/mobile/src/theme/tokens.generated.ts  (the ThemeTokens tree consumed by DEFAULT_THEME)
 *   - apps/admin/src/styles/tokens.generated.css (`--token-*` CSS vars the admin palette aliases)
 * so the two apps can never hand-drift from the design tokens.
 *
 * Usage:
 *   node scripts/gen-tokens.mjs           # write the generated files
 *   node scripts/gen-tokens.mjs --check   # fail (exit 1) if committed output is stale (CI)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokensPath = resolve(root, 'design/tokens.json');
const mobileOut = resolve(root, 'apps/mobile/src/theme/tokens.generated.ts');
const adminOut = resolve(root, 'apps/admin/src/styles/tokens.generated.css');

const BANNER = 'GENERATED by scripts/gen-tokens.mjs from design/tokens.json — DO NOT EDIT.';

function loadTokens() {
  const raw = JSON.parse(readFileSync(tokensPath, 'utf-8'));
  delete raw.$meta; // documentation only, not part of the token tree
  return raw;
}

function renderMobile(tokens) {
  const body = JSON.stringify(tokens, null, 2);
  return (
    `/* ${BANNER} */\n` +
    `import type { ThemeTokens } from '@repo/shared-types';\n\n` +
    `export const GENERATED_DEFAULT_THEME: ThemeTokens = ${body} as ThemeTokens;\n`
  );
}

function renderAdmin(tokens) {
  const varsFor = (palette) =>
    Object.entries(palette)
      .flatMap(([group, entries]) =>
        Object.entries(entries).map(
          ([key, value]) => `  --token-${group}-${kebab(key)}: ${value};`,
        ),
      )
      .join('\n');
  return (
    `/* ${BANNER} */\n` +
    `:root,\n[data-theme='dark'] {\n${varsFor(tokens.color)}\n}\n\n` +
    `[data-theme='light'] {\n${varsFor(tokens.colorLight)}\n}\n`
  );
}

function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

const tokens = loadTokens();
const outputs = [
  [mobileOut, renderMobile(tokens)],
  [adminOut, renderAdmin(tokens)],
];

const check = process.argv.includes('--check');
let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    const current = safeRead(path);
    if (current !== content) {
      stale = true;
      console.error(`✗ ${path} is out of sync with design/tokens.json`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`✓ wrote ${path}`);
  }
}

function safeRead(path) {
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    return null;
  }
}

if (check && stale) {
  console.error("Run 'pnpm gen:tokens' and commit the regenerated files.");
  process.exit(1);
}
if (check) console.log('✓ design tokens are in sync.');
