/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json — DO NOT EDIT. */
import type { ThemeTokens } from '@repo/shared-types';

export const GENERATED_DEFAULT_THEME: ThemeTokens = {
  "color": {
    "brand": {
      "primary": "#E5E2E1",
      "onPrimary": "#1C1B1B",
      "secondary": "#E6B450",
      "accent": "#5E5CE6",
      "onAccent": "#FFFFFF",
      "indigo": "#5E5CE6",
      "onIndigo": "#FFFFFF",
      "gold": "#E6B450",
      "onGold": "#1A1408"
    },
    "bg": {
      "base": "#050505",
      "surface": "#121414",
      "elevated": "#1A1A1C",
      "container": "#1E2020",
      "sidebar": "#0D0E0F",
      "scrim": "rgba(0,0,0,0.60)"
    },
    "text": {
      "primary": "#E2E2E2",
      "secondary": "#A1A1A6",
      "muted": "#8E9192",
      "faint": "#5F5E5E",
      "inverse": "#1C1B1B"
    },
    "state": {
      "success": "#5CC48F",
      "warning": "#E6B450",
      "error": "#FFB4AB",
      "info": "#5E5CE6",
      "purple": "#C2C1FF",
      "credit": "#5E5CE6",
      "debit": "#FFB4AB"
    },
    "border": {
      "default": "#282A2B",
      "soft": "#1E2020",
      "strong": "#333535",
      "ghost": "rgba(226,226,226,0.15)",
      "focus": "#5E5CE6"
    }
  },
  "colorLight": {
    "brand": {
      "primary": "#5E5CE6",
      "onPrimary": "#FFFFFF",
      "secondary": "#9A6C15",
      "accent": "#4B49C4",
      "onAccent": "#FFFFFF",
      "indigo": "#5E5CE6",
      "onIndigo": "#FFFFFF",
      "gold": "#E6B450",
      "onGold": "#1A1408"
    },
    "bg": {
      "base": "#F5F4F0",
      "surface": "#FFFFFF",
      "elevated": "#FAF9F5",
      "container": "#F1EFE9",
      "sidebar": "#FBFAF7",
      "scrim": "rgba(20,22,28,0.40)"
    },
    "text": {
      "primary": "#1A1C20",
      "secondary": "#454A52",
      "muted": "#767C85",
      "faint": "#A3A8B0",
      "inverse": "#FFFFFF"
    },
    "state": {
      "success": "#1F9D5F",
      "warning": "#9A6C15",
      "error": "#D64D43",
      "info": "#4B49C4",
      "purple": "#7C4FD0",
      "credit": "#4B49C4",
      "debit": "#D64D43"
    },
    "border": {
      "default": "#E5E2DA",
      "soft": "#EDEAE2",
      "strong": "#D9D5CB",
      "ghost": "rgba(20,22,28,0.10)",
      "focus": "#4B49C4"
    }
  },
  "typography": {
    "fontFamily": {
      "display": "Playfair Display",
      "sans": "Inter",
      "mono": "JetBrains Mono"
    },
    "scale": {
      "display": {
        "font": "display",
        "size": 34,
        "lineHeight": 40,
        "weight": 700,
        "letterSpacing": "-0.01em"
      },
      "h1": {
        "font": "display",
        "size": 28,
        "lineHeight": 34,
        "weight": 600,
        "letterSpacing": "-0.01em"
      },
      "h2": {
        "font": "display",
        "size": 22,
        "lineHeight": 28,
        "weight": 600
      },
      "title": {
        "font": "sans",
        "size": 15,
        "lineHeight": 22,
        "weight": 700
      },
      "body": {
        "font": "sans",
        "size": 15,
        "lineHeight": 24,
        "weight": 400
      },
      "bodySm": {
        "font": "sans",
        "size": 13,
        "lineHeight": 20,
        "weight": 400
      },
      "label": {
        "font": "sans",
        "size": 12,
        "lineHeight": 16,
        "weight": 600,
        "uppercase": true,
        "letterSpacing": "0.1em"
      },
      "kicker": {
        "font": "sans",
        "size": 10.5,
        "lineHeight": 13,
        "weight": 600,
        "uppercase": true,
        "letterSpacing": "0.16em"
      },
      "mono": {
        "font": "mono",
        "size": 13,
        "lineHeight": 18,
        "weight": 500,
        "letterSpacing": "-0.01em"
      }
    }
  },
  "radius": {
    "control": 16,
    "card": 16,
    "wallet": 12,
    "image": 24,
    "pill": 999,
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 24
  },
  "spacing": {
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32,
    "2xl": 48,
    "safe": 24,
    "section": 64
  },
  "shadow": {
    "sm": "0 1px 2px rgba(0,0,0,0.50)",
    "md": "0 8px 24px rgba(0,0,0,0.45)",
    "glass": "0 8px 40px rgba(0,0,0,0.55)",
    "cardLight": "0 1px 2px rgba(20,22,28,.05), 0 1px 3px rgba(20,22,28,.05)",
    "ghost": "inset 0.5px 0.5px 0 rgba(226,226,226,0.15)",
    "indigoGlow": "0 0 0 1px rgba(94,92,230,0.35)",
    "goldGlow": "0 0 0 1px rgba(230,180,80,0.35)"
  },
  "components": {
    "buttonPrimary": {
      "bg": "brand.primary",
      "fg": "brand.onPrimary",
      "radius": "pill",
      "height": 48
    },
    "buttonAccent": {
      "bg": "brand.accent",
      "fg": "brand.onAccent",
      "radius": "pill",
      "height": 48
    },
    "buttonSecondary": {
      "bg": "transparent",
      "fg": "text.primary",
      "border": "border.ghost",
      "radius": "pill",
      "height": 44
    },
    "card": {
      "bg": "bg.elevated",
      "border": "border.ghost",
      "radius": "card",
      "shadow": "glass"
    },
    "glassCard": {
      "bg": "bg.elevated",
      "border": "border.ghost",
      "radius": "card",
      "blur": 28,
      "opacity": 0.7
    },
    "immersiveCard": {
      "radius": "image",
      "scrim": "linear-gradient(180deg, rgba(5,5,5,0) 30%, rgba(5,5,5,0.85) 100%)"
    },
    "walletCard": {
      "bg": "bg.container",
      "border": "border.ghost",
      "radius": "wallet",
      "chip": "brand.accent"
    },
    "input": {
      "bg": "transparent",
      "border": "border.ghost",
      "radius": "control",
      "placeholder": "text.muted"
    },
    "sidebar": {
      "bg": "bg.sidebar",
      "width": 250
    },
    "topbar": {
      "bg": "bg.base",
      "height": 64
    },
    "tabbar": {
      "bg": "bg.elevated",
      "border": "border.ghost",
      "radius": "pill",
      "blur": 32,
      "active": "brand.accent",
      "floatOffset": 16
    },
    "statusPill": {
      "radius": "pill",
      "dot": true
    },
    "hairline": {
      "color": "border.ghost",
      "thickness": 0.5,
      "inset": 24
    },
    "toggle": {
      "onTrack": "brand.accent",
      "onKnob": "brand.onAccent",
      "offTrack": "border.soft",
      "offKnob": "text.faint"
    }
  }
} as ThemeTokens;
